# Configure Datasources.

# First, define the data-sources themselves.
# Each datasource has a "name", optionally a "no_facets" indicator, 
# optionally a list of supported "viewstyles" (list, compact, grid?), and
# a detailed configuration for it's "search_box"
# 
# Next, define the "datasource_bar", really the list
# of datasources presented in the sidebar, divided
# into "major" and "minor", to control display.
# 
datasources:

  quicksearch:
    name: Quicksearch
    no_facets: true
    search_box:
      route: quicksearch_index_path
      placeholder: Catalog, Articles, Academic Commons, Library Web 

  newspapers:
    name: Newspapers
    search_box:
      route: newspapers_index_path
      placeholder: Newspapers
      search_type: summon
      advanced: true
      # search_category: newspapers
      search_fields:
        q: Keywords
        s.fq[AuthorCombined]: Author
        s.fq[TitleCombined]: Title
        s.fq[ISBN]: ISBN
        s.fq[ISSN]: ISSN

  articles:
    name: Articles
    search_box:
      route: articles_index_path
      placeholder: Articles
      search_type: summon
      advanced: true
      # search_category: articles
      search_fields:
        q: Keywords
        s.fq[AuthorCombined]: Author
        s.fq[TitleCombined]: Title
        # NEXT-581 - articles search by publication title
        s.fq[PublicationTitle]: Publication Title
        s.fq[ISBN]: ISBN
        s.fq[ISSN]: ISSN

  ebooks:
    name: E-Books
    no_facets: true
    search_box:
      route: ebooks_index_path
      placeholder: E-Books 

  dissertations:
    name: Dissertations
    no_facets: true
    search_box:
      route: dissertations_index_path
      placeholder: Dissertations

  catalog:
    name: Catalog
    viewstyles: 
      list: Standard View
      compact: Compact View
    viewstyles_DISABLED: 
      list: Standard View
      compact: Compact View
      spartan: Title View
    default_viewstyle: list
    search_box:
      route: base_catalog_index_path
      placeholder: Catalog
      search_type: blacklight
      advanced: true
      search_fields:
        all_fields: All Fields
        title: Title
        journal_title: Journal Title
        author: Author
        series_title: Series
        title_starts_with: Title Begins With
        subject: Subject
        form_genre: Form/Genre
        publication_place: Publication Place
        publisher: Publisher
        publication_year: Publication Year
        isbn: ISBN
        issn: ISSN
        call_number: Call Number
        location: Location

  archives:
    name: Archives
    search_box:
      advanced: true
      route: archives_index_path
      placeholder: Archives
      search_type: blacklight
      search_fields:
        all_fields: All Fields
        title: Title
        author: Author
        subject: Subject

  databases:
    name: Databases
    search_box:
      advanced: true
      route: databases_index_path 
      placeholder: Databases
      search_type: blacklight
      search_fields:
        all_fields: All Fields
        title: Title
        author: Author
        subject: Subject

  journals:
    name: E-Journal Titles
    search_box:
      advanced: true
      route: journals_index_path
      placeholder: E-Journal Titles
      search_type: blacklight
      search_fields:
        all_fields: All Fields
        title: Title
        title_starts_with: Title Begins With
        subject: Subject
        issn: ISSN

  library_web:
    name: Libraries Website
    no_facets: true
    search_box:
      route: library_web_index_path
      placeholder: Libraries Website

  academic_commons:
    name: Academic Commons
    search_box:
      route: academic_commons_index_path
      placeholder: Academic Commons
      search_type: blacklight
      search_fields:
        all_fields: All Fields
        title: Title
        author: Author
        subject: Subject

  new_arrivals:
    name: New Arrivals
    search_box:
      route: new_arrivals_index_path
      placeholder: New Arrivals
      advanced: true
      search_type: blacklight
      search_fields:
        all_fields: All Fields
        title: Title
        journal_title: Journal Title
        author: Author
        subject: Subject


datasource_bar:
  major_sources:
    - quicksearch
    - catalog
    - articles
    - journals
    - databases
    - academic_commons
    - library_web
  minor_sources:
    - archives
    - dissertations
    - ebooks
    - new_arrivals
    - newspapers

