layouts:
  articles:
    style: summon
    has_facets: true
    columns:
      - searches:
          - source: articles 
  library_web:
    style: single
    columns:
      - searches:
          - source: library_web 
            # let per-page (row count) be parameterized
            # count: 10
  quicksearch:
    style: aggregate
    columns:
      - width: 6
        searches:
          - source: catalog
            count: 10
            display_footer: true
            row_opts:
              spans: [3,9] 
      - width: 6
        searches:
          - source: articles
            count: 3
            row_opts:
              spans: [3,9] 
          - source: academic_commons
            count: 3
            row_opts:
              spans: [3,9]

          - source: library_web
            count: 3
            row_opts:
              spans: [3,9]
  newspapers:
    style: summon
    has_facets: true
    columns:
      - searches:
          - source: newspapers 
  dissertations:
    style: aggregate
    columns:
      - width: 6
        searches:
          - source: catalog_dissertations
            count: 10
            display_footer: true
            row_opts:
              spans: [3,9] 
      - width: 6
        searches:
          - source: dissertations
            count: 3
            row_opts:
              spans: [3,9] 
          - source: ac_dissertations 
            count: 3
            row_opts:
              spans: [3,9] 
  ebooks:
    style: aggregate
    columns:
      - width: 6
        searches:
          - source: catalog_ebooks 
            count: 10
            display_footer: true
            row_opts:
              spans: [3,9] 
      - width: 6
        searches:
          - source: ebooks 
            count: 10
            display_footer: true
            row_opts:
              spans: [3,9]
sources:
  quicksearch:
    warning: 
  archives:
    warningXX: Archives is busted!
  new_arrivals:
    warningXX: New Arrivals is busted!
  catalog:
    title: Catalog
    description: Contains library, books, videos, local resources
    warningXX:  Catalog is broken!
    holdings_check: true
    render_options:
      format: clio
  articles:
    title: Articles
    description: Contains articles, eBooks, electronic resources
    warningXX: We are currently experiencing performance problems with this datasource.  We are working with the vendor to resolve this issue.
    render_options:
      format: article
  academic_commons:
    title: Academic Commons
    description: Digital Repository of Research 
    warningXX:  Item Status unavailable due to system upgrades.  AC.
    render_options:
      format: ac
      check_fedora: true
  library_web:
    title: Libraries Website
    description: Searches the libraries' website
    warningXX:  Item Status unavailable due to system upgrades.  LWEB.
    render_options:
      format: lweb
  ac_dissertations:
    title: Academic Commons
    description: Dissertations from Columbia's Digital Repository
    warningXX:  Item Status unavailable due to system upgrades.  AC-DISS.
    render_options:
      format: ac
      check_fedora: true
  dissertations:
    title: Summon
    description: Dissertations from Columbia's Articles Database
    warningXX: We are currently experiencing performance problems with this datasource.  We are working with the vendor to resolve this issue.  ArtyDiss.
    render_options:
      format: article
  newspapers:
    title: Newspaper Articles
    description: Full text newspaper articles from Summon
    warningXX: We are currently experiencing performance problems with this datasource.  We are working with the vendor to resolve this issue.  ArtyNews.
    render_options:
      format: article
  databases:
    title: Databases
    description: Electronic resources
    warningXX:  Item Status unavailable due to system upgrades.  CAT-DB.
    render_options:
      format: clio
  catalog_dissertations:
    title: Catalog
    description: Dissertations, Thesises from Columbia's Catalog
    warningXX:  Item Status unavailable due to system upgrades.  CAT-DISS.
    render_options:
      format: clio
  catalog_ebooks:
    title: Catalog
    description: eBooks from Catalog
    warningXX:  Item Status unavailable due to system upgrades.  CAT-EBOO.
    render_options:
      format: clio
  journals:
    title: Journal Titles
    description: Electronic Journals Held By Columbia
    warningXX:  Item Status unavailable due to system upgrades.  CAT-JOURNALS.
    render_options:
      format: clio 
  ebooks:
    title: Summon
    description: eBooks from Summon's repository of digitzed books
    warningXX: We are currently experiencing performance problems with this datasource.  We are working with the vendor to resolve this issue.  eboo.
    render_options:
      format: ebooks


